library(tidyverse)

options("scipen"=3)

escreve_arquivo <- function(n, n_arquivo, arquivo_arquivos)
{

    arquivo <- paste0("D:\\doutorado\\APA\\matches\\entradasbruno\\entrada_",n,"_",n_arquivo,".csv")

    cabecalho <- tibble( v1 = c("RANDOM INSTANCE STABLE MARIAGE"))
    
    elementos <- tibble(v1 = "N", v2 = c(as.integer(n)) )
    
    cabecalho_men <- tibble( v1 = c("MEN'S PREFERENCES"))
    
    pref_men <- as.tibble(t(replicate(n,sample(0:(n-1),n ))))
    
    cabecalho_women <- tibble( v1 = c("WOMEN'S PREFERENCES"))
    
    pref_women <- as.tibble(t(replicate(n,sample(0:(n-1),n ))))
    
    rodape <- tibble( v1 = c("<Generated by Bruno Crotman, 2019>"))
    
    write_delim(cabecalho, arquivo, delim = " ", col_names = FALSE, append = FALSE) 
    write_delim(elementos, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(rodape, arquivo, delim = " ", col_names = FALSE, append = TRUE) 

    tibble_arquivo <- tibble( v1 = arquivo )


    write_delim(tibble_arquivo, arquivo_arquivos, col_names = FALSE,  append = TRUE)
    
   
    

}


escreve_arquivo_best <- function(n, n_arquivo, arquivo_arquivos)
{
    
    arquivo <- paste0("D:\\doutorado\\APA\\matches\\entradas_melhor_bruno\\best_sm_",n,".txt")
    
    cabecalho <- tibble( v1 = c("RANDOM INSTANCE STABLE MARIAGE"))
    
    elementos <- tibble(v1 = "N", v2 = c(as.integer(n)) )
    
    cabecalho_men <- tibble( v1 = c("MEN'S PREFERENCES"))
    
    pref_men <- as.tibble(   matrix( as.integer( ((0:(n*n-1)) + ((0: (n*n-1)   )%/%n)   )%%n   )  ,nrow = n, byrow = TRUE))  
    
    cabecalho_women <- tibble( v1 = c("WOMEN'S PREFERENCES"))
    
    pref_women <- as.tibble(matrix(  as.integer(  ((0:(n*n-1)) + ((0: (n*n-1)   )%/%n)   )%%n  )   ,nrow = n, byrow = TRUE))
    
    rodape <- tibble( v1 = c("<Generated by Bruno Crotman, 2019>"))
    
    write_delim(cabecalho, arquivo, delim = " ", col_names = FALSE, append = FALSE) 
    write_delim(elementos, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(rodape, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    
    tibble_arquivo <- tibble( v1 = arquivo )
    
    
    write_delim(tibble_arquivo, arquivo_arquivos, col_names = FALSE,  append = TRUE)

}



escreve_arquivo_worst <- function(n, n_arquivo, arquivo_arquivos)
{
    
    arquivo <- paste0("D:\\doutorado\\APA\\matches\\entradas_pior_bruno\\hard_sm_",n,".txt")
    
    cabecalho <- tibble( v1 = c("RANDOM INSTANCE STABLE MARIAGE"))
    
    elementos <- tibble(v1 = "N", v2 = c(as.integer(n)) )
    
    cabecalho_men <- tibble( v1 = c("MEN'S PREFERENCES"))
    
    n_menos_1 <- as.integer( n-1)
    
    pref_men_pre <- matrix(   as.integer(  (  as.integer((0:(n_menos_1*n_menos_1-1))) + as.integer((0: (n_menos_1*n_menos_1-1)   )%/%n_menos_1)   )%%n_menos_1  )   ,nrow = n, byrow = TRUE )
    
    pref_men <- as.tibble(  cbind(pref_men_pre, as.integer(n-1)) ) 
    
    cabecalho_women <- tibble( v1 = c("WOMEN'S PREFERENCES"))
    
    pref_women <- as.tibble(matrix(  as.integer(  ((1:(n*n)) + ((0: (n*n-1)   )%/%n)   )%%n   )  ,nrow = n, byrow = TRUE))
    
    rodape <- tibble( v1 = c("<Generated by Bruno Crotman, 2019>"))
    
    write_delim(cabecalho, arquivo, delim = " ", col_names = FALSE, append = FALSE) 
    write_delim(elementos, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_men, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(cabecalho_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(pref_women, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    write_delim(rodape, arquivo, delim = " ", col_names = FALSE, append = TRUE) 
    
    tibble_arquivo <- tibble( v1 = arquivo )
    
    
    write_delim(tibble_arquivo, arquivo_arquivos, col_names = FALSE,  append = TRUE)
    
}





rodadas <- tibble(rodada = 1:1) %>% 
    crossing(tibble(n = c(
                  5, 
                  50, 
                  100, 
                  200, 
                  300, 
                  400, 
                  500, 
                  600, 
                  700, 
                  800, 
                  900,
                  1000, 
                  1500, 
                  2000, 
                  2500, 
                  3000, 
                  4000, 
                  5000,
                  6000,
                  7000,
                  8000,
                  9000
                  ) )
             ) %>% 
    mutate(arquivo_arquivos = "D:\\doutorado\\APA\\matches\\entradasbruno\\arquivos_ale_best.csv", um = 1) %>% 
    mutate(n_arquivo = cumsum(um)) %>% 
    rowwise() %>% 
    #do(escreve_arquivo(n = .$n, arquivo_arquivos = .$arquivo_arquivos, n_arquivo = .$n_arquivo)) %>% 
    do(escreve_arquivo_best(n = .$n, arquivo_arquivos = .$arquivo_arquivos, n_arquivo = .$rodada)) %>% 
    identity() 










